### ISSUE TITLE
missing chapter 9 to 21

### ISSUE THREAD

**Issue by username7171** [geonaut/Fluent-Python#1]
is the maintainer still working on the code,     if not, i guess i am willing to do the work.  It is a great book

**Comment by geonaut** [comment]
I got a job, so didn't have time to complete my Jupyter notebooks for the book. Happy to accept PRs for the other chapters, if they are just personal notes on the chapters.

**Comment by geonaut** [comment]
Agree - it is a good book for levelling up your Python
